In [20]:
import numpy as np

In [18]:
a=np.random.randint(1,10,10)
b=np.random.randint(1,10,10)

In [19]:
a,b

(array([3, 6, 2, 8, 2, 9, 3, 6, 5, 8]), array([4, 6, 3, 4, 7, 5, 4, 3, 2, 3]))

In [20]:
z=np.empty(len(a),dtype=int)
for i in range(len(a)):
    z[i]=a[i]+b[i]
z

array([ 7, 12,  5, 12,  9, 14,  7,  9,  7, 11])

In [21]:
z.shape

(10,)

### 2-D matrices

In [22]:
a=np.random.randint(1,10,(5,4))
b=np.random.randint(1,10,(5,4))

In [23]:
a,b

(array([[5, 8, 7, 9],
        [7, 4, 2, 2],
        [7, 3, 9, 2],
        [7, 1, 1, 3],
        [9, 7, 4, 8]]), array([[5, 8, 2, 2],
        [7, 2, 1, 4],
        [6, 7, 8, 5],
        [5, 1, 2, 5],
        [6, 7, 4, 8]]))

In [25]:
a[0][1]

8

In [27]:
z=np.empty(a.shape,dtype=int)
for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        z[i][j]=a[i][j]+b[i][j]

In [28]:
z

array([[10, 16,  9, 11],
       [14,  6,  3,  6],
       [13, 10, 17,  7],
       [12,  2,  3,  8],
       [15, 14,  8, 16]])

In [30]:
a=np.random.randint(1,10,(4,4))
b=np.random.randint(1,10,(4,4))

In [31]:
a

array([[1, 7, 5, 4],
       [4, 8, 2, 6],
       [2, 4, 6, 4],
       [2, 1, 3, 1]])

In [32]:
b

array([[7, 4, 6, 8],
       [6, 9, 7, 6],
       [5, 6, 5, 9],
       [6, 4, 8, 8]])

In [34]:
res=np.empty(a.shape,dtype=int)
for i in range(a.shape[0]):
    for j in range(b.shape[1]):
        res[i][j]=a[i][j]+b[i][j]

In [35]:
res

array([[ 8, 11, 11, 12],
       [10, 17,  9, 12],
       [ 7, 10, 11, 13],
       [ 8,  5, 11,  9]])

In [21]:
# addition of 3-d matrix
a=np.random.randint(1,10,(3,3,3))
b=np.random.randint(1,10,(3,3,3))
c=np.random.randint(1,10,(3,3,3))

In [40]:
a[2,:,:]
# a

array([[6, 4, 1],
       [6, 4, 7],
       [7, 3, 4]])

In [41]:
a

array([[[6, 2, 2],
        [2, 3, 2],
        [2, 4, 9]],

       [[2, 3, 7],
        [3, 5, 1],
        [4, 3, 9]],

       [[6, 4, 1],
        [6, 4, 7],
        [7, 3, 4]]])

In [24]:
res=np.empty(a.shape)
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        for k in range(a.shape[2]):
            res[i,j,k]=a[i,j,k]+b[i,j,k]
print(res)

[[[ 9.  5.  6.]
  [ 6.  7.  4.]
  [ 9.  9. 18.]]

 [[ 4.  7. 12.]
  [ 6.  8.  8.]
  [ 6. 12. 13.]]

 [[10.  7.  9.]
  [14.  8.  8.]
  [10.  9.  7.]]]


### find if given point is inside or outside the circle

In [44]:
import math

In [50]:
def inside_or_outside(cx,cy,r,x,y):
    if math.sqrt((cx-x)**2+(cy-y)**2)<=r:
        return 'Inside'
    else:
        return 'Outside'

In [52]:
inside_or_outside(2,3,5,2,88)

'Outside'

In [54]:
a=np.random.randint(1,10,(4,5,6))

In [56]:
np.reshape(a,-1,'C')

array([2, 8, 9, 2, 9, 4, 7, 2, 1, 4, 5, 1, 6, 4, 8, 7, 3, 3, 5, 7, 4, 9,
       5, 3, 2, 2, 7, 6, 5, 9, 3, 6, 6, 4, 7, 6, 3, 6, 8, 5, 7, 9, 3, 5,
       2, 4, 4, 7, 8, 4, 3, 8, 2, 2, 2, 8, 5, 2, 6, 6, 2, 7, 3, 1, 8, 3,
       3, 4, 5, 1, 8, 5, 9, 2, 8, 6, 8, 2, 9, 8, 8, 4, 5, 9, 8, 4, 9, 8,
       3, 9, 7, 5, 4, 4, 7, 7, 9, 4, 5, 7, 3, 1, 3, 1, 9, 6, 2, 3, 1, 6,
       2, 6, 9, 3, 5, 7, 5, 4, 7, 7])

In [57]:
np.reshape(a,(10,-1),'C')

array([[2, 8, 9, 2, 9, 4, 7, 2, 1, 4, 5, 1],
       [6, 4, 8, 7, 3, 3, 5, 7, 4, 9, 5, 3],
       [2, 2, 7, 6, 5, 9, 3, 6, 6, 4, 7, 6],
       [3, 6, 8, 5, 7, 9, 3, 5, 2, 4, 4, 7],
       [8, 4, 3, 8, 2, 2, 2, 8, 5, 2, 6, 6],
       [2, 7, 3, 1, 8, 3, 3, 4, 5, 1, 8, 5],
       [9, 2, 8, 6, 8, 2, 9, 8, 8, 4, 5, 9],
       [8, 4, 9, 8, 3, 9, 7, 5, 4, 4, 7, 7],
       [9, 4, 5, 7, 3, 1, 3, 1, 9, 6, 2, 3],
       [1, 6, 2, 6, 9, 3, 5, 7, 5, 4, 7, 7]])

In [71]:
a=np.random.randint(1,10,(5,4,3))
b=np.random.randint(1,10,(7,4,3))
# print(a,b)

In [73]:
np.concatenate((a,b),axis=1)

ValueError: all the input array dimensions except for the concatenation axis must match exactly